kind = "DojoContract"
class_hash = "0x30844a62e81412ec39dcb1bbb9ead29f431487a027a570110b30b0d99973708"
original_class_hash = "0x30844a62e81412ec39dcb1bbb9ead29f431487a027a570110b30b0d99973708"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/mancala_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "mancala::systems::actions::actions"
